
export type DayStatus = 'completed' | 'failed' | 'break' | 'none';

export interface Milestone {
  id: string;
  dayIndex: number;
  label: string;
  date: string;
  emoji?: string;
  reward?: string;
  isAutoGenerated?: boolean;
}

export interface Habit {
  id: string;
  name: string;
  color: string;
  frequency: number;
  history: Record<string, DayStatus>;
  milestones: Milestone[];
  cumulativeTarget?: number;
  rewardTemplate?: string;
  emojiTemplate?: string;
  createdAt: string;
  isArchived?: boolean; // Nuevo campo para archivado
}

export interface DailyTask {
  id: string;
  text: string;
  completed: boolean;
}

export interface DailyObjectiveRecord {
  date: string; // ISO YYYY-MM-DD
  tasks: DailyTask[];
  status: 'pending' | 'checked' | 'failed';
}

export interface AppDataExport {
  habits: Habit[];
  dailyHistory: DailyObjectiveRecord[];
  currentDaily: DailyObjectiveRecord;
  motivation: string;
  exportedAt: string;
}

export type ViewMode = 'overview' | 'individual' | 'group' | 'trophies' | 'daily_objectives';

export const MONTHS = [
  'Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 
  'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic'
];

export const NEON_COLORS = {
  LIME: '#afff00',
  CYAN: '#00f0ff',
  VIOLET: '#bc00ff',
  PINK: '#ff007a',
  ORANGE: '#ff8a00'
};
